# stage 1
FROM python:3.12-slim AS builder

RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /build
COPY app/requirement.txt .
RUN pip install --prefix=/install --no-cache-dir -r requirement.txt

# stage 2
FROM python:3.12-slim

WORKDIR /backend
COPY --from=builder /install /usr/local
COPY app /backend/app

EXPOSE 5001
CMD ["uvicorn", "app.ml_server:app", "--host", "0.0.0.0", "--port", "5001"]