FROM python:3.11-slim

# Install minimal OS deps
RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential git curl ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /mlflow
VOLUME ["/mlflow"]
EXPOSE 8000

CMD ["mlflow", "server", "--backend-store-uri", "sqlite:///mlflow.db", "--host", "0.0.0.0", "--port", "8000"]
