# stage 1
FROM apache/airflow:3.1.1-python3.12 AS builder
USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    python3-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow
WORKDIR /home/airflow
COPY dags/lib/requirements.txt .
RUN pip install --user --no-cache-dir -r requirements.txt

# stage 2
FROM apache/airflow:3.1.1-python3.12 
USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    unzip \
    curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/airflow
COPY --from=builder /home/airflow/.local /home/airflow/.local
ENV PATH="/home/airflow/.local/bin:$PATH"
USER airflow