name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'frontend/**'
      - 'airflow/**'
      - '.github/workflows/*.yml'
      - 'docker-compose.prod.yml'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      packages: write

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    secrets:
      GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      CREDENTIAL: ${{ secrets.CREDENTIAL }}
    with:
      docker_tag: ${{ needs.build.outputs.docker_tag }}
    permissions:
      contents: read
      packages: read

  healthcheck:
    needs: deploy
    uses: ./.github/workflows/healthcheck.yml
